name: pytest with redefine
on:
  pull_request:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          # ssh key is for private submodules
          ssh-key: ${{ secrets.CI_SSH_KEY }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        run: |
          pip install pytest
      # Test python
      - name: Test pytest with redefine
        run: |
          echo ${GITHUB_REF_NAME}
          git checkout --quiet feature/pytests_for_e2e
          git checkout --quiet MergeBaseTestBase
          git checkout --quiet -
          export GITHUB_BASE_REF="MergeBaseTestBase"; \
          export GITHUB_HEAD_REF="feature/pytests_for_e2e"; \
          export REDEFINE_COYOTE_GIT_PATH=${{ github.workspace }}
          export REDEFINE_CUSTOMER_ID="REDEFINE_TESTREPO"; \
          export CI_TYPE="GITHUB"; \
          export REDEFINE_RELEASE_NAME="canary"; \
          wget -q https://redefine-installation-public.s3.eu-west-1.amazonaws.com/canary/redefine_installation -O /tmp/redefine_installation; \
          chmod u+x /tmp/redefine_installation; \
          /tmp/redefine_installation
          pytest -sv || true
